### ISSUE TITLE
Deployment failure

### ISSUE THREAD

**Issue by RMeli** [conda-forge/spyrmsd-feedstock#6]
The CI in PR #5 came back green so I merged, but [Azure Pipelines](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=205788&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3) is now failing and the package has not been updated. Anything I can do to fix this problem @conda-forge/core?

**Comment by beckermr** [comment]
you need to rerender the feedstock as instructed in PR #5

**Comment by RMeli** [comment]
Thank you for the fast reply @beckermr ! I did it the previous times and nothing happened, so this time I must have skipped it.

Should I open a new PR with the build number bumped?

**Comment by beckermr** [comment]
No need to bump the build number since nothing ever got uploaded to the main channels.

**Comment by beckermr** [comment]
A new PR is needed yes.

**Comment by RMeli** [comment]
Got it, thank you very much!
